// Comprehensive exercise library used by the custom program builder.
// Each entry's `category` maps to an existing swap_category — keeps the
// muscle-tracking logic in muscles.js and the dashboard grid working.

export const EXERCISE_LIBRARY = [
  // ── Chest (compound) ──────────────────────────────────────────────────────
  { name: 'Barbell Bench Press',          category: 'chest_multi',  muscle: 'Chest',     equipment: 'Barbell' },
  { name: 'Dumbbell Bench Press',         category: 'chest_multi',  muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Incline Barbell Press',        category: 'chest_multi',  muscle: 'Chest',     equipment: 'Barbell' },
  { name: 'Incline Dumbbell Press',       category: 'chest_multi',  muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Decline Barbell Press',        category: 'chest_multi',  muscle: 'Chest',     equipment: 'Barbell' },
  { name: 'Decline Dumbbell Press',       category: 'chest_multi',  muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Smith Machine Bench Press',    category: 'chest_multi',  muscle: 'Chest',     equipment: 'Machine' },
  { name: 'Dumbbell Floor Press',         category: 'chest_multi',  muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Push-Up',                      category: 'chest_multi',  muscle: 'Chest',     equipment: 'Bodyweight' },
  { name: 'Wide Push-Up',                 category: 'chest_multi',  muscle: 'Chest',     equipment: 'Bodyweight' },
  // ── Chest (isolation) ─────────────────────────────────────────────────────
  { name: 'Cable Crossover',              category: 'chest_single', muscle: 'Chest',     equipment: 'Cable' },
  { name: 'Dumbbell Flye',                category: 'chest_single', muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Flye',        category: 'chest_single', muscle: 'Chest',     equipment: 'Dumbbell' },
  { name: 'Pec Deck / Machine Flye',      category: 'chest_single', muscle: 'Chest',     equipment: 'Machine' },
  { name: 'Cable Flye (Low to High)',     category: 'chest_single', muscle: 'Chest',     equipment: 'Cable' },
  { name: 'Cable Flye (High to Low)',     category: 'chest_single', muscle: 'Chest',     equipment: 'Cable' },
  { name: 'Svend Press',                  category: 'chest_single', muscle: 'Chest',     equipment: 'Plates' },
  // ── Shoulders ─────────────────────────────────────────────────────────────
  { name: 'Barbell Overhead Press',       category: 'shoulders',    muscle: 'Shoulders', equipment: 'Barbell' },
  { name: 'Dumbbell Shoulder Press',      category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Arnold Press',                 category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Seated DB Shoulder Press',     category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Machine Shoulder Press',       category: 'shoulders',    muscle: 'Shoulders', equipment: 'Machine' },
  { name: 'Lateral Raise (DB)',           category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Lateral Raise (Cable)',        category: 'shoulders',    muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Front Raise (DB)',             category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Front Raise (Cable)',          category: 'shoulders',    muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Face Pull',                    category: 'shoulders',    muscle: 'Shoulders', equipment: 'Cable' },
  { name: 'Rear Delt Flye (DB)',          category: 'shoulders',    muscle: 'Shoulders', equipment: 'Dumbbell' },
  { name: 'Rear Delt Flye (Machine)',     category: 'shoulders',    muscle: 'Shoulders', equipment: 'Machine' },
  // ── Triceps ───────────────────────────────────────────────────────────────
  { name: 'Cable Pushdown (Rope)',        category: 'triceps',      muscle: 'Triceps',   equipment: 'Cable' },
  { name: 'Cable Pushdown (Bar)',         category: 'triceps',      muscle: 'Triceps',   equipment: 'Cable' },
  { name: 'Overhead Tricep Ext (DB)',     category: 'triceps',      muscle: 'Triceps',   equipment: 'Dumbbell' },
  { name: 'Overhead Tricep Ext (Cable)',  category: 'triceps',      muscle: 'Triceps',   equipment: 'Cable' },
  { name: 'Skull Crusher (EZ Bar)',       category: 'triceps',      muscle: 'Triceps',   equipment: 'Barbell' },
  { name: 'Close-Grip Bench Press',       category: 'triceps',      muscle: 'Triceps',   equipment: 'Barbell' },
  { name: 'Tricep Dip (Parallel Bars)',   category: 'triceps',      muscle: 'Triceps',   equipment: 'Bodyweight' },
  { name: 'Diamond Push-Up',              category: 'triceps',      muscle: 'Triceps',   equipment: 'Bodyweight' },
  { name: 'Kickback (DB)',                category: 'triceps',      muscle: 'Triceps',   equipment: 'Dumbbell' },
  { name: 'JM Press',                    category: 'triceps',      muscle: 'Triceps',   equipment: 'Barbell' },
  // ── Back (compound) ───────────────────────────────────────────────────────
  { name: 'Barbell Row (Overhand)',       category: 'back_multi',   muscle: 'Back',      equipment: 'Barbell' },
  { name: 'Barbell Row (Underhand)',      category: 'back_multi',   muscle: 'Back',      equipment: 'Barbell' },
  { name: 'T-Bar Row',                   category: 'back_multi',   muscle: 'Back',      equipment: 'Barbell' },
  { name: 'Seated Cable Row',            category: 'back_multi',   muscle: 'Back',      equipment: 'Cable' },
  { name: 'Pull-Up',                     category: 'back_multi',   muscle: 'Back',      equipment: 'Bodyweight' },
  { name: 'Wide-Grip Pull-Up',           category: 'back_multi',   muscle: 'Back',      equipment: 'Bodyweight' },
  { name: 'Chin-Up',                     category: 'back_multi',   muscle: 'Back',      equipment: 'Bodyweight' },
  { name: 'Lat Pulldown (Wide)',         category: 'back_multi',   muscle: 'Back',      equipment: 'Cable' },
  { name: 'Lat Pulldown (Neutral Grip)', category: 'back_multi',   muscle: 'Back',      equipment: 'Cable' },
  { name: 'Chest-Supported Row',         category: 'back_multi',   muscle: 'Back',      equipment: 'Machine' },
  { name: 'Dumbbell Row',               category: 'back_multi',   muscle: 'Back',      equipment: 'Dumbbell' },
  { name: 'Pendlay Row',                category: 'back_multi',   muscle: 'Back',      equipment: 'Barbell' },
  // ── Back (isolation) ──────────────────────────────────────────────────────
  { name: 'Straight-Arm Pulldown',      category: 'back_single',  muscle: 'Back',      equipment: 'Cable' },
  { name: 'Single-Arm Cable Row',       category: 'back_single',  muscle: 'Back',      equipment: 'Cable' },
  { name: 'Dumbbell Pullover',          category: 'back_single',  muscle: 'Back',      equipment: 'Dumbbell' },
  { name: 'Cable Pullover',             category: 'back_single',  muscle: 'Back',      equipment: 'Cable' },
  { name: 'Back Extension / Hyper',     category: 'back_single',  muscle: 'Back',      equipment: 'Bodyweight' },
  // ── Traps ─────────────────────────────────────────────────────────────────
  { name: 'Barbell Shrug',              category: 'traps',        muscle: 'Traps',     equipment: 'Barbell' },
  { name: 'Dumbbell Shrug',             category: 'traps',        muscle: 'Traps',     equipment: 'Dumbbell' },
  { name: 'Cable Shrug',                category: 'traps',        muscle: 'Traps',     equipment: 'Cable' },
  { name: 'Smith Machine Shrug',        category: 'traps',        muscle: 'Traps',     equipment: 'Machine' },
  { name: 'Rack Pull',                  category: 'traps',        muscle: 'Traps',     equipment: 'Barbell' },
  { name: 'Deadlift',                   category: 'traps',        muscle: 'Traps',     equipment: 'Barbell' },
  { name: 'Upright Row',                category: 'traps',        muscle: 'Traps',     equipment: 'Barbell' },
  { name: "Farmer's Carry",             category: 'traps',        muscle: 'Traps',     equipment: 'Dumbbell' },
  // ── Biceps ────────────────────────────────────────────────────────────────
  { name: 'Barbell Curl',               category: 'biceps',       muscle: 'Biceps',    equipment: 'Barbell' },
  { name: 'EZ Bar Curl',                category: 'biceps',       muscle: 'Biceps',    equipment: 'Barbell' },
  { name: 'Dumbbell Curl',              category: 'biceps',       muscle: 'Biceps',    equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Curl',      category: 'biceps',       muscle: 'Biceps',    equipment: 'Dumbbell' },
  { name: 'Hammer Curl',                category: 'biceps',       muscle: 'Biceps',    equipment: 'Dumbbell' },
  { name: 'Cable Curl (Bar)',           category: 'biceps',       muscle: 'Biceps',    equipment: 'Cable' },
  { name: 'Cable Curl (Rope)',          category: 'biceps',       muscle: 'Biceps',    equipment: 'Cable' },
  { name: 'Concentration Curl',         category: 'biceps',       muscle: 'Biceps',    equipment: 'Dumbbell' },
  { name: 'Preacher Curl',              category: 'biceps',       muscle: 'Biceps',    equipment: 'Barbell' },
  { name: 'Spider Curl',                category: 'biceps',       muscle: 'Biceps',    equipment: 'Dumbbell' },
  // ── Legs (compound) ───────────────────────────────────────────────────────
  { name: 'Back Squat',                 category: 'legs_multi',   muscle: 'Legs',      equipment: 'Barbell' },
  { name: 'Front Squat',                category: 'legs_multi',   muscle: 'Legs',      equipment: 'Barbell' },
  { name: 'Leg Press',                  category: 'legs_multi',   muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Hack Squat',                 category: 'legs_multi',   muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Goblet Squat',               category: 'legs_multi',   muscle: 'Legs',      equipment: 'Dumbbell' },
  { name: 'Bulgarian Split Squat',      category: 'legs_multi',   muscle: 'Legs',      equipment: 'Dumbbell' },
  { name: 'Barbell Lunge',              category: 'legs_multi',   muscle: 'Legs',      equipment: 'Barbell' },
  { name: 'Walking Lunge',              category: 'legs_multi',   muscle: 'Legs',      equipment: 'Dumbbell' },
  { name: 'Step-Up',                    category: 'legs_multi',   muscle: 'Legs',      equipment: 'Dumbbell' },
  { name: 'Romanian Deadlift',          category: 'legs_multi',   muscle: 'Legs',      equipment: 'Barbell' },
  { name: 'Sumo Deadlift',              category: 'legs_multi',   muscle: 'Legs',      equipment: 'Barbell' },
  // ── Legs (isolation) ──────────────────────────────────────────────────────
  { name: 'Leg Extension',              category: 'legs_single',  muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Leg Curl (Lying)',           category: 'legs_single',  muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Leg Curl (Seated)',          category: 'legs_single',  muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Hip Thrust (Barbell)',       category: 'legs_single',  muscle: 'Legs',      equipment: 'Barbell' },
  { name: 'Glute Bridge',               category: 'legs_single',  muscle: 'Legs',      equipment: 'Bodyweight' },
  { name: 'Single-Leg Press',           category: 'legs_single',  muscle: 'Legs',      equipment: 'Machine' },
  { name: 'Cable Kickback',             category: 'legs_single',  muscle: 'Legs',      equipment: 'Cable' },
  { name: 'Nordic Hamstring Curl',      category: 'legs_single',  muscle: 'Legs',      equipment: 'Bodyweight' },
  // ── Calves ────────────────────────────────────────────────────────────────
  { name: 'Standing Calf Raise',        category: 'calves',       muscle: 'Calves',    equipment: 'Machine' },
  { name: 'Seated Calf Raise',          category: 'calves',       muscle: 'Calves',    equipment: 'Machine' },
  { name: 'Leg Press Calf Raise',       category: 'calves',       muscle: 'Calves',    equipment: 'Machine' },
  { name: 'Single-Leg Calf Raise',      category: 'calves',       muscle: 'Calves',    equipment: 'Bodyweight' },
  { name: 'Smith Machine Calf Raise',   category: 'calves',       muscle: 'Calves',    equipment: 'Machine' },
  { name: 'Donkey Calf Raise',          category: 'calves',       muscle: 'Calves',    equipment: 'Bodyweight' },
  { name: 'Tibialis Raise',             category: 'calves',       muscle: 'Calves',    equipment: 'Bodyweight' },
  // ── Abs ───────────────────────────────────────────────────────────────────
  { name: 'Plank',                      category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Ab Wheel Rollout',           category: 'abs',          muscle: 'Abs',       equipment: 'Other' },
  { name: 'Cable Crunch',               category: 'abs',          muscle: 'Abs',       equipment: 'Cable' },
  { name: 'Hanging Leg Raise',          category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Decline Crunch',             category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Russian Twist',              category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Dead Bug',                   category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Bicycle Crunch',             category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Hollow Body Hold',           category: 'abs',          muscle: 'Abs',       equipment: 'Bodyweight' },
  { name: 'Landmine Twist',             category: 'abs',          muscle: 'Abs',       equipment: 'Barbell' },
]

export const MUSCLE_FILTERS = [
  'All', 'Chest', 'Shoulders', 'Triceps', 'Back', 'Traps', 'Biceps', 'Legs', 'Calves', 'Abs',
]

// ── Warm-up library ───────────────────────────────────────────────────────────
export const WARMUP_LIBRARY = [
  { name: 'Jumping Jacks',               duration: '2 min' },
  { name: 'Jump Rope',                   duration: '3 min' },
  { name: 'High Knees',                  duration: '1 min' },
  { name: 'Butt Kicks',                  duration: '1 min' },
  { name: 'Leg Swings (front/back)',     duration: '15 each leg' },
  { name: 'Leg Swings (side to side)',   duration: '15 each leg' },
  { name: 'Hip Circles',                 duration: '10 each way' },
  { name: 'Arm Circles',                 duration: '30 sec each way' },
  { name: 'Shoulder Rolls',              duration: '10 each way' },
  { name: 'Inchworm',                    duration: '5 reps' },
  { name: "World's Greatest Stretch",    duration: '5 each side' },
  { name: 'Thoracic Rotation',           duration: '10 each side' },
  { name: 'Hip Flexor Stretch (dynamic)',duration: '10 each side' },
  { name: 'Cat-Cow',                     duration: '10 reps' },
  { name: 'Glute Bridge (bodyweight)',   duration: '2×15' },
  { name: 'Clamshells',                  duration: '2×15 each side' },
  { name: 'Band Pull-Aparts',            duration: '2×15' },
  { name: 'Band Face Pull',              duration: '2×15' },
  { name: 'Shoulder CARs',              duration: '5 each side' },
  { name: 'Hip CARs',                   duration: '5 each side' },
]

// ── Cool-down library ─────────────────────────────────────────────────────────
export const COOLDOWN_LIBRARY = [
  { name: 'Static Hamstring Stretch',    duration: '30 sec each' },
  { name: 'Hip Flexor Stretch',          duration: '30 sec each' },
  { name: 'Quad Stretch',                duration: '30 sec each' },
  { name: 'Pigeon Pose',                 duration: '60 sec each' },
  { name: 'Figure-4 Stretch',            duration: '30 sec each' },
  { name: 'Seated Spinal Twist',         duration: '30 sec each' },
  { name: 'Child\'s Pose',              duration: '60 sec' },
  { name: 'Chest Doorframe Stretch',     duration: '30 sec' },
  { name: 'Lat Stretch',                 duration: '30 sec each' },
  { name: 'Standing Calf Stretch',       duration: '30 sec each' },
  { name: 'Upper Back Stretch',          duration: '30 sec' },
  { name: 'Neck Stretch',                duration: '30 sec each side' },
  { name: 'Seated Hamstring Stretch',    duration: '30 sec each' },
  { name: 'Foam Roll Quads',             duration: '60 sec each' },
  { name: 'Foam Roll IT Band',           duration: '60 sec each' },
  { name: 'Foam Roll Upper Back',        duration: '60 sec' },
  { name: 'Foam Roll Calves',            duration: '60 sec each' },
  { name: 'Box Breathing',               duration: '2 min' },
]
